# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ChuJiTwo.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1343, 820)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/tupian/logo.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setWindowOpacity(1.0)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color:rgb(0, 0, 0)")
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setStyleSheet("background-color: rgb(0, 85, 127);")
        self.widget.setObjectName("widget")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setStyleSheet("border-image: url(:/tupian/智能斑马线.png);")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setStyleSheet("background-color: rgb(0, 85, 127);\n"
"border-image: url(:/tupian/标题边框T.png);\n"
"\n"
"color: rgb(255, 255, 255);\n"
"font: 87 25pt \"Segoe UI\";")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setStyleSheet("\n"
"border-image: url(:/tupian/标题边框T.png);\n"
"color: rgb(255, 255, 255);\n"
"font: 90 14pt \"Segoe UI\";\n"
"")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.horizontalLayout.setStretch(0, 2)
        self.horizontalLayout.setStretch(1, 8)
        self.horizontalLayout.setStretch(2, 2)
        self.verticalLayout_7.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.shipinliebiaoButton = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(3)
        self.shipinliebiaoButton.setFont(font)
        self.shipinliebiaoButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.shipinliebiaoButton.setStyleSheet("QPushButton{\n"
"\n"
"        border:2px solid rgb(88, 199, 238);\n"
"        color:#FFFFFF;\n"
"        font: 25 15pt \"Segoe UI\";\n"
"        height:40px;\n"
"        padding-left:10px;\n"
"        padding-right:10px;\n"
"        border-radius:5px;\n"
"    }\n"
"    QPushButton:hover{\n"
"        color:black;\n"
"        font: 25 16pt \"Segoe UI\";;\n"
"        border:1px solid #FFFFFF;\n"
"        border-radius:5px;\n"
"        \n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgb(221, 221, 221), stop:2 rgb(255, 255, 255),stop:1 rgb(164, 190, 217));\n"
"    color: rgb(0, 0, 0);\n"
"    }\n"
"")
        self.shipinliebiaoButton.setObjectName("shipinliebiaoButton")
        self.verticalLayout_5.addWidget(self.shipinliebiaoButton)
        self.shipinliebiao = QtWidgets.QListWidget(self.widget)
        self.shipinliebiao.setToolTipDuration(-1)
        self.shipinliebiao.setStyleSheet("QListWidget{\n"
"    color: rgb(255, 255, 255);\n"
"    selection-color: rgb(170, 255, 0);\n"
"        border-image: url(:/tupian/标题边框T.png);\n"
"\n"
"       font: \"思源宋体\";\n"
"        font-size:20px;\n"
"        padding:15px;\n"
"        lint-height:100px\n"
"    }")
        self.shipinliebiao.setIconSize(QtCore.QSize(50, 50))
        self.shipinliebiao.setObjectName("shipinliebiao")
        self.verticalLayout_5.addWidget(self.shipinliebiao)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.DispalyLabel = QtWidgets.QLabel(self.widget)
        self.DispalyLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.DispalyLabel.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-image: url(:/tupian/龙背景.png);\n"
"\n"
"\n"
"")
        self.DispalyLabel.setText("")
        self.DispalyLabel.setScaledContents(True)
        self.DispalyLabel.setObjectName("DispalyLabel")
        self.horizontalLayout_2.addWidget(self.DispalyLabel)
        self.line = QtWidgets.QFrame(self.widget)
        self.line.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_2.addWidget(self.line)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(-1, 0, -1, 2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSpacing(7)
        self.gridLayout.setObjectName("gridLayout")
        self.lcdNumber = QtWidgets.QLCDNumber(self.widget)
        self.lcdNumber.setStyleSheet("color: rgb(252, 233, 79);")
        self.lcdNumber.setSmallDecimalPoint(True)
        self.lcdNumber.setDigitCount(3)
        self.lcdNumber.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber.setProperty("value", 0.0)
        self.lcdNumber.setProperty("intValue", 0)
        self.lcdNumber.setObjectName("lcdNumber")
        self.gridLayout.addWidget(self.lcdNumber, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(3)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(238, 238, 236);\n"
"font: 25 11pt \"Ubuntu\";")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(3)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(238, 238, 236);\n"
"font: 25 11pt \"Ubuntu\";")
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 0, 1, 1)
        self.horizontalSlider = QtWidgets.QSlider(self.widget)
        self.horizontalSlider.setSizeIncrement(QtCore.QSize(2, 2))
        self.horizontalSlider.setBaseSize(QtCore.QSize(2, 2))
        self.horizontalSlider.setMouseTracking(False)
        self.horizontalSlider.setMaximum(100)
        self.horizontalSlider.setSingleStep(10)
        self.horizontalSlider.setPageStep(10)
        self.horizontalSlider.setProperty("value", 30)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.gridLayout.addWidget(self.horizontalSlider, 4, 0, 2, 2)
        self.lcdNumber_2 = QtWidgets.QLCDNumber(self.widget)
        self.lcdNumber_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.lcdNumber_2.setStyleSheet("color:rgb(204, 0, 0)")
        self.lcdNumber_2.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_2.setProperty("intValue", 0)
        self.lcdNumber_2.setObjectName("lcdNumber_2")
        self.gridLayout.addWidget(self.lcdNumber_2, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.textEdit = QtWidgets.QTextEdit(self.widget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.textEdit.setFont(font)
        self.textEdit.setStyleSheet("QTextEdit{\n"
"        font: 8pt \"Segoe UI\";\n"
"        color:#232C51;\n"
"        background:white;\n"
"        border-radius:8px;\n"
"border:4px solid rgb(88, 199, 238);\n"
"\n"
"}")
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout.addWidget(self.textEdit)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 4)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout_2.setStretch(0, 2)
        self.horizontalLayout_2.setStretch(1, 8)
        self.horizontalLayout_2.setStretch(2, 1)
        self.horizontalLayout_2.setStretch(3, 2)
        self.verticalLayout_7.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.radioButtonCam = QtWidgets.QRadioButton(self.widget)
        self.radioButtonCam.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.radioButtonCam.setMouseTracking(True)
        self.radioButtonCam.setStyleSheet("QRadioButton{\n"
"        border-radius:10px;\n"
"\n"
"        color:#FFFFFF;\n"
"        font-size:20px;\n"
"        height:20px;\n"
"        padding-left:10px;\n"
"        padding-right:10px;\n"
"    }\n"
"    QRadioButton:hover{\n"
"        color:black;\n"
"        border:1px solid #FFFFFF;\n"
"        border-radius:10px;\n"
"        background:LightGray;\n"
"    }\n"
"")
        self.radioButtonCam.setObjectName("radioButtonCam")
        self.verticalLayout_2.addWidget(self.radioButtonCam)
        self.radioButtonFile = QtWidgets.QRadioButton(self.widget)
        self.radioButtonFile.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.radioButtonFile.setStyleSheet("QRadioButton{\n"
"        border-radius:10px;\n"
"\n"
"        color:#FFFFFF;\n"
"        font-size:20px;\n"
"        height:20px;\n"
"        padding-left:10px;\n"
"        padding-right:10px;\n"
"    }\n"
"    QRadioButton:hover{\n"
"        color:black;\n"
"        border:1px solid #FFFFFF;\n"
"        border-radius:10px;\n"
"        background:LightGray;\n"
"    }\n"
"")
        self.radioButtonFile.setObjectName("radioButtonFile")
        self.verticalLayout_2.addWidget(self.radioButtonFile)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 1)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        spacerItem = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(198, 17, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.Open = QtWidgets.QPushButton(self.widget)
        self.Open.setMinimumSize(QtCore.QSize(0, 0))
        self.Open.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Open.setStyleSheet("QPushButton{\n"
"\n"
"        border:2px solid rgb(88, 199, 238);\n"
"        color:#FFFFFF;\n"
"        font: 25 12pt \"Segoe UI\";\n"
"        height:40px;\n"
"        padding-left:10px;\n"
"        padding-right:10px;\n"
"        border-radius:5px;\n"
"    }\n"
"    QPushButton:hover{\n"
"        color:black;\n"
"        font: 25 14pt \"Segoe UI\";\n"
"        border:1px solid #FFFFFF;\n"
"        border-radius:5px;\n"
"        \n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgb(221, 221, 221), stop:2 rgb(255, 255, 255),stop:1 rgb(164, 190, 217));\n"
"    color: rgb(0, 0, 0);\n"
"    }\n"
"")
        self.Open.setObjectName("Open")
        self.horizontalLayout_3.addWidget(self.Open)
        spacerItem2 = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.First = QtWidgets.QPushButton(self.widget)
        self.First.setMinimumSize(QtCore.QSize(0, 0))
        self.First.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.First.setStyleSheet("QPushButton{\n"
"\n"
"        border:2px solid rgb(88, 199, 238);\n"
"        color:#FFFFFF;\n"
"        font: 25 12pt \"Segoe UI\";\n"
"        height:40px;\n"
"        padding-left:10px;\n"
"        padding-right:10px;\n"
"        border-radius:5px;\n"
"    }\n"
"    QPushButton:hover{\n"
"        color:black;\n"
"        font: 25 14pt \"Segoe UI\";\n"
"        border:1px solid #FFFFFF;\n"
"        border-radius:5px;\n"
"        \n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgb(221, 221, 221), stop:2 rgb(255, 255, 255),stop:1 rgb(164, 190, 217));\n"
"    color: rgb(0, 0, 0);\n"
"    }\n"
"")
        self.First.setObjectName("First")
        self.horizontalLayout_3.addWidget(self.First)
        spacerItem3 = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.Close = QtWidgets.QPushButton(self.widget)
        self.Close.setMinimumSize(QtCore.QSize(0, 0))
        self.Close.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Close.setToolTip("")
        self.Close.setStyleSheet("QPushButton{\n"
"\n"
"        border:2px solid rgb(88, 199, 238);\n"
"        color:#FFFFFF;\n"
"        font: 25 12pt \"Segoe UI\";\n"
"        height:40px;\n"
"        padding-left:10px;\n"
"        padding-right:10px;\n"
"        border-radius:5px;\n"
"    }\n"
"    QPushButton:hover{\n"
"        color:black;\n"
"        font: 25 14pt \"Segoe UI\";\n"
"        border:1px solid #FFFFFF;\n"
"        border-radius:5px;\n"
"        \n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgb(221, 221, 221), stop:2 rgb(255, 255, 255),stop:1 rgb(164, 190, 217));\n"
"    color: rgb(0, 0, 0);\n"
"    }\n"
"")
        self.Close.setObjectName("Close")
        self.horizontalLayout_3.addWidget(self.Close)
        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(2, 1)
        self.horizontalLayout_3.setStretch(4, 1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        spacerItem4 = QtWidgets.QSpacerItem(198, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem4)
        self.horizontalLayout_4.addLayout(self.verticalLayout_3)
        spacerItem5 = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_8 = QtWidgets.QLabel(self.widget)
        self.label_8.setStyleSheet("font: 12pt \"Segoe UI\";\n"
"background-color: rgb(0, 85, 127);\n"
"color: rgb(255, 255, 255);")
        self.label_8.setObjectName("label_8")
        self.verticalLayout_4.addWidget(self.label_8)
        self.label_9 = QtWidgets.QLabel(self.widget)
        self.label_9.setStyleSheet("font: 12pt \"Segoe UI\";\n"
"background-color: rgb(0, 85, 127);\n"
"color: rgb(255, 255, 255);")
        self.label_9.setObjectName("label_9")
        self.verticalLayout_4.addWidget(self.label_9)
        self.verticalLayout_4.setStretch(0, 1)
        self.verticalLayout_4.setStretch(1, 1)
        self.horizontalLayout_4.addLayout(self.verticalLayout_4)
        self.horizontalLayout_4.setStretch(0, 2)
        self.horizontalLayout_4.setStretch(2, 6)
        self.horizontalLayout_4.setStretch(3, 1)
        self.horizontalLayout_4.setStretch(4, 2)
        self.verticalLayout_7.addLayout(self.horizontalLayout_4)
        self.verticalLayout_7.setStretch(0, 1)
        self.verticalLayout_7.setStretch(1, 10)
        self.verticalLayout_7.setStretch(2, 1)
        self.verticalLayout_8.addLayout(self.verticalLayout_7)
        self.verticalLayout_6.addWidget(self.widget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1343, 26))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.toolBar.setMouseTracking(True)
        self.toolBar.setTabletTracking(True)
        self.toolBar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.toolBar.setAutoFillBackground(False)
        self.toolBar.setStyleSheet("background-color: rgb(205, 219, 232);")
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.shipin = QtWidgets.QAction(MainWindow)
        self.shipin.setCheckable(True)
        self.shipin.setChecked(False)
        self.shipin.setEnabled(True)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/tupian/视频 (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.shipin.setIcon(icon1)
        self.shipin.setAutoRepeat(True)
        self.shipin.setObjectName("shipin")
        self.close_2 = QtWidgets.QAction(MainWindow)
        self.close_2.setCheckable(True)
        self.close_2.setChecked(False)
        self.close_2.setObjectName("close_2")
        self.open_2 = QtWidgets.QAction(MainWindow)
        self.open_2.setCheckable(True)
        self.open_2.setChecked(False)
        self.open_2.setEnabled(True)
        self.open_2.setObjectName("open_2")
        self.shexinagtou = QtWidgets.QAction(MainWindow)
        self.shexinagtou.setCheckable(True)
        self.shexinagtou.setChecked(False)
        self.shexinagtou.setEnabled(True)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/tupian/摄像头1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.shexinagtou.setIcon(icon2)
        font = QtGui.QFont()
        self.shexinagtou.setFont(font)
        self.shexinagtou.setShortcutContext(QtCore.Qt.WindowShortcut)
        self.shexinagtou.setAutoRepeat(True)
        self.shexinagtou.setVisible(True)
        self.shexinagtou.setMenuRole(QtWidgets.QAction.TextHeuristicRole)
        self.shexinagtou.setIconVisibleInMenu(True)
        self.shexinagtou.setObjectName("shexinagtou")
        self.tuanduixinxi = QtWidgets.QAction(MainWindow)
        self.tuanduixinxi.setCheckable(True)
        self.tuanduixinxi.setChecked(False)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/tupian/团队2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tuanduixinxi.setIcon(icon3)
        self.tuanduixinxi.setObjectName("tuanduixinxi")
        self.caozuoshuoming = QtWidgets.QAction(MainWindow)
        self.caozuoshuoming.setCheckable(True)
        self.caozuoshuoming.setChecked(False)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/tupian/操作说明.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.caozuoshuoming.setIcon(icon4)
        self.caozuoshuoming.setWhatsThis("")
        self.caozuoshuoming.setObjectName("caozuoshuoming")
        self.zuixiaohua = QtWidgets.QAction(MainWindow)
        self.zuixiaohua.setCheckable(True)
        self.zuixiaohua.setChecked(False)
        self.zuixiaohua.setEnabled(True)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/tupian/最小化.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.zuixiaohua.setIcon(icon5)
        font = QtGui.QFont()
        self.zuixiaohua.setFont(font)
        self.zuixiaohua.setObjectName("zuixiaohua")
        self.zuidahua = QtWidgets.QAction(MainWindow)
        self.zuidahua.setCheckable(True)
        self.zuidahua.setChecked(False)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("../../../../../dell/.designer/backup/TuPian/最大化.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.zuidahua.setIcon(icon6)
        self.zuidahua.setObjectName("zuidahua")
        self.action_3 = QtWidgets.QAction(MainWindow)
        self.action_3.setCheckable(True)
        self.action_3.setChecked(False)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("../../../../../dell/.designer/backup/TuPian/团队.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_3.setIcon(icon7)
        self.action_3.setObjectName("action_3")
        self.action_4 = QtWidgets.QAction(MainWindow)
        self.action_4.setCheckable(True)
        self.action_4.setChecked(False)
        self.action_4.setObjectName("action_4")
        self.menu.addAction(self.shexinagtou)
        self.menu.addSeparator()
        self.menu.addAction(self.shipin)
        self.menu.addSeparator()
        self.menu.addAction(self.close_2)
        self.menu.addSeparator()
        self.menu.addAction(self.open_2)
        self.menu_2.addSeparator()
        self.menu_2.addAction(self.tuanduixinxi)
        self.menu_2.addAction(self.caozuoshuoming)
        self.menu_3.addAction(self.zuixiaohua)
        self.menu_3.addSeparator()
        self.menu_3.addAction(self.zuidahua)
        self.menu_3.addSeparator()
        self.menu_3.addAction(self.action_3)
        self.menu_3.addSeparator()
        self.menu_3.addAction(self.action_4)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.toolBar.addAction(self.shexinagtou)
        self.toolBar.addSeparator()
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.shipin)
        self.toolBar.addSeparator()
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.tuanduixinxi)
        self.toolBar.addSeparator()
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.caozuoshuoming)

        self.retranslateUi(MainWindow)
        self.shexinagtou.changed.connect(MainWindow.radioButtonCam2)
        self.shipin.changed.connect(MainWindow.radioButtonFile2)
        self.tuanduixinxi.changed.connect(MainWindow.tuanduixinxi1)
        self.close_2.changed.connect(MainWindow.close)
        self.open_2.changed.connect(MainWindow.Open1)
        self.caozuoshuoming.changed.connect(MainWindow.caozuoshuoming1)
        self.Open.clicked.connect(MainWindow.Open1)
        self.Close.clicked.connect(MainWindow.Close1)
        self.radioButtonCam.clicked.connect(MainWindow.radioButtonCam1)
        self.First.clicked.connect(MainWindow.suspend_continue1)
        self.radioButtonFile.clicked.connect(MainWindow.radioButtonFile1)
        self.shipinliebiao.doubleClicked['QModelIndex'].connect(MainWindow.open2)
        self.shipinliebiaoButton.clicked.connect(MainWindow.clicked)
        self.zuixiaohua.changed.connect(MainWindow.Zuixiaohua)
        self.zuidahua.changed.connect(MainWindow.Zuidahua)
        self.action_3.changed.connect(MainWindow.tuanduixinxi1)
        self.action_4.changed.connect(MainWindow.caozuoshuoming1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "云汉识别"))
        self.label_2.setText(_translate("MainWindow", "云汉——行人识别与跟踪"))
        self.label_3.setText(_translate("MainWindow", "TextLabe"))
        self.shipinliebiaoButton.setToolTip(_translate("MainWindow", "点击检索本地视频"))
        self.shipinliebiaoButton.setText(_translate("MainWindow", "视频列表   检索"))
        self.shipinliebiao.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">  双击 查看视频  </span></p></body></html>"))
        self.label.setText(_translate("MainWindow", "累计人流量:"))
        self.label_5.setText(_translate("MainWindow", "选择置信度："))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:12pt;\">输出结果信息：</span></p></body></html>"))
        self.radioButtonCam.setToolTip(_translate("MainWindow", "点击选择打开摄像头"))
        self.radioButtonCam.setText(_translate("MainWindow", "  摄像头"))
        self.radioButtonFile.setToolTip(_translate("MainWindow", "点击选择本地文件"))
        self.radioButtonFile.setText(_translate("MainWindow", "  本地文件"))
        self.Open.setToolTip(_translate("MainWindow", "不点击视频列表是可直接点击打开查找本地视频"))
        self.Open.setText(_translate("MainWindow", "打开"))
        self.First.setText(_translate("MainWindow", "暂 停"))
        self.Close.setText(_translate("MainWindow", "关 闭"))
        self.label_8.setText(_translate("MainWindow", "指导老师：  姚保琛"))
        self.label_9.setText(_translate("MainWindow", "成员：  冯龙亭  邰光雄  刘东林"))
        self.menu.setTitle(_translate("MainWindow", "文件"))
        self.menu_2.setTitle(_translate("MainWindow", "帮助"))
        self.menu_3.setTitle(_translate("MainWindow", "窗口"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.shipin.setText(_translate("MainWindow", "本地视频"))
        self.shipin.setToolTip(_translate("MainWindow", "本地视频 Ctrl+W"))
        self.shipin.setStatusTip(_translate("MainWindow", "从电脑选取视频"))
        self.shipin.setWhatsThis(_translate("MainWindow", "66666666666"))
        self.shipin.setShortcut(_translate("MainWindow", "Ctrl+W"))
        self.close_2.setText(_translate("MainWindow", "关闭"))
        self.close_2.setToolTip(_translate("MainWindow", "关闭 Ctrl+X"))
        self.close_2.setShortcut(_translate("MainWindow", "Ctrl+X"))
        self.open_2.setText(_translate("MainWindow", "打开"))
        self.open_2.setToolTip(_translate("MainWindow", "打开 Ctrl+O"))
        self.open_2.setStatusTip(_translate("MainWindow", "初始状态默认打开摄像头"))
        self.open_2.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.shexinagtou.setText(_translate("MainWindow", "摄像头"))
        self.shexinagtou.setToolTip(_translate("MainWindow", "摄像头 Ctrl+C"))
        self.shexinagtou.setStatusTip(_translate("MainWindow", "打开摄像头"))
        self.shexinagtou.setShortcut(_translate("MainWindow", "Ctrl+C"))
        self.tuanduixinxi.setText(_translate("MainWindow", "团队信息"))
        self.tuanduixinxi.setToolTip(_translate("MainWindow", "团队信息 Ctrl+/"))
        self.tuanduixinxi.setStatusTip(_translate("MainWindow", "查看制作团队信息"))
        self.tuanduixinxi.setShortcut(_translate("MainWindow", "Ctrl+/"))
        self.caozuoshuoming.setText(_translate("MainWindow", "操作说明"))
        self.caozuoshuoming.setToolTip(_translate("MainWindow", "操作说明 Ctrl+P"))
        self.caozuoshuoming.setStatusTip(_translate("MainWindow", "查看操作说明"))
        self.caozuoshuoming.setShortcut(_translate("MainWindow", "Ctrl+P"))
        self.zuixiaohua.setText(_translate("MainWindow", "最小化"))
        self.zuixiaohua.setStatusTip(_translate("MainWindow", "窗口最小化"))
        self.zuixiaohua.setShortcut(_translate("MainWindow", "Ctrl+M"))
        self.zuidahua.setText(_translate("MainWindow", "最大化"))
        self.zuidahua.setStatusTip(_translate("MainWindow", "窗口最大化"))
        self.action_3.setText(_translate("MainWindow", "团队介绍"))
        self.action_3.setStatusTip(_translate("MainWindow", "打开团队介绍窗口"))
        self.action_3.setShortcut(_translate("MainWindow", "Ctrl+T"))
        self.action_4.setText(_translate("MainWindow", "操作说明"))
        self.action_4.setStatusTip(_translate("MainWindow", "打开操作说明窗口"))
        self.action_4.setShortcut(_translate("MainWindow", "Ctrl+H"))
import tupian_rc
